image: takkatakka/lftp

stages:
  - deploy

before_script:
  - mkdir ~/.ssh
  - echo "$SSH_KEY" > ~/.ssh/id_rsa
  - ssh-keyscan -H '$HOST'
  - chmod -R 700 ~/.ssh
  - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'

deploy:
  stage: deploy
  script:
    - lftp -c "set ftp:ssl-allow no; open -u $USERNAME,$PASSWORD $HOST; cd prod; mirror -Rnev --parallel=10 --exclude .env --exclude .git/ --exclude data/ --exclude logs/ --exclude node_modules/ "
    - ssh -l $USERNAME $HOST 'cd prod ; yarn install ; yarn build'
    - ssh -l $USERNAME $HOST 'sudo systemctl restart erin'
  variables:
    NODE_ENV: production
  environment:
    name: production
  rules:
    - if: '$CI_COMMIT_REF_NAME == "master"'
    - when: manual
