on:
  workflow_dispatch:
  push:
    branches:
      - master
      - test

jobs:  
  deploy:
    runs-on: ubuntu-latest
    environment: production
    steps:
    - name: Checkout 
      uses: actions/checkout@v2 # Required to mount the Github Workspace to a volume 
    - name: Copy
      uses: easingthemes/ssh-deploy@main
      env:
        SSH_PRIVATE_KEY: ${{ SSH_KEY }}
        ARGS: "-rltgoDzvO --delete"          
        REMOTE_HOST: ${{ HOST }}
        REMOTE_USER: ${{ USERNAME }}
        TARGET: "prod/"
        EXCLUDE: "data/, node_modules/, logs/, .git/"
    
    - name: Configure SSH
      run: |
        mkdir -p ~/.ssh/
        echo "$SSH_KEY" > ~/.ssh/staging.key
        chmod 600 ~/.ssh/staging.key
        cat >>~/.ssh/config <<END
          Host staging
          HostName $SSH_HOST
          User $SSH_USER
          IdentityFile ~/.ssh/staging.key
            StrictHostKeyChecking no
          END
      env:
        SSH_USER: ${{ USERNAME }}
        SSH_KEY: ${{ SSH_KEY }}
        SSH_HOST: ${{ HOST }}

    - name: Install and build
      run: ssh staging 'cd prod ; yarn install ; yarn build'
    - name: Restart
      run: ssh staging 'sudo systemctl restart erin'
